
## LabDS01 ##


The following dataset includes information about several countries. This information was collected by the world bank (https://data.worldbank.org/). Data corresponds to 2016.

`
dataFile="https://raw.githubusercontent.com/masterfloss/data/main/worlddata2016.xlsx"
df=pd.read_excel(dataFile)
`

# 1. Business Understanding

Purpose: Analyse data and extract knowledge

Observation: Country

In [1]:
import pandas as pd
import numpy as np
dataFile="https://raw.githubusercontent.com/masterfloss/data/main/worlddata2016.xlsx"
df=pd.read_excel(dataFile)

In [2]:
df.head()

,Unnamed: 0,Country Name,Indicator Name,2016
0,0,Afghanistan,Access to clean fuels and technologies for coo...,32.44000
1,1,Afghanistan,Access to electricity (% of population),97.70000
2,2,Afghanistan,"Access to electricity, rural (% of rural popul...",97.09936
3,3,Afghanistan,"Access to electricity, urban (% of urban popul...",99.50000
4,4,Afghanistan,Account ownership at a financial institution o...,NaN

In [3]:
#ver se os valores estao em numerico
df.dtypes

Unnamed: 0          int64
Country Name       object
Indicator Name     object
2016              float64
dtype: object

# 2. Data Undertanding

* Discuss the data and purposes
* What are the main limitations?

In [4]:
#tenho que passar os indicadores para colunas
#um dos problemas é que há muitas variáveis, ou buscamos as variaveis todas que serão usadas especificamente ou eliminar variaveis ou analise fatoriais
df1=pd.pivot_table(df, values='2016', index=['Country Name'], columns=['Indicator Name'])
#verify 
df1.head()

Indicator Name,ARI treatment (% of children under 5 taken to a health provider),Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adequacy of social insurance programs (% of total welfare of beneficiary households),Adequacy of social protection and labor programs (% of total welfare of beneficiary households),Adequacy of social safety net programs (% of total welfare of beneficiary households),Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households),"Adjusted net enrollment rate, primary (% of primary school age children)",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),Young people (ages 15-24) newly infected with HIV
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,32.44,97.700000,97.099360,99.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.7,500.0
Albania,NaN,77.42,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,97.65542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.6,100.0
Algeria,NaN,92.62,99.990051,99.965142,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.4,500.0
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,100.00,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#1300 variàveis (aconcelho evitar tantas)
df1.shape

(217, 1328)

In [6]:
df1.index.name='country'

# 3. Data Preparation

* Converting data to numeric
* Missing Values Imputation
* Normalization
* Variable Dummification
* Data balancing
* Pivot date in order to convert the values "Indicator Name" into comuns 
* Remove all columns that have no values, df1[columns].sum()==0
* Remove all columns that have more than 210 observations, df1[columns].count()<210

In [10]:
#converter all 0 into nan
df2=df2.replace(0,np.nan)

In [17]:
#remove all columns that have no values

for column1 in df2:
    if df2[column1].count()<210:
        df2=df2.drop([column1], axis=1)

In [19]:
df2.shape()

TypeError: 'tuple' object is not callable

In [20]:
df2.head()

Indicator Name,Access to electricity (% of population),"Access to electricity, urban (% of urban population)",Adjusted savings: mineral depletion (current US$),Agricultural land (sq. km),Capture fisheries production (metric tons),Forest area (sq. km),Land area (sq. km),People using at least basic drinking water services (% of population),Population density (people per sq. km of land area),Population growth (annual %),...,Rural population (% of total population),Secure Internet servers,Secure Internet servers (per 1 million people),Surface area (sq. km),Terrestrial and marine protected areas (% of total territorial area),Terrestrial protected areas (% of total land area),Total fisheries production (metric tons),Urban population,Urban population (% of total population),Urban population growth (annual %)
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,97.700000,99.5,9.110295e+05,379100.000000,1000.0,13500.000000,652860.0,64.286484,54.197114,2.778317,...,74.980,426.0,12.039637,652860.0,0.104707,0.10,2200.0,8852859.0,25.020,3.649410
Albania,100.000000,100.0,9.287008e+05,11816.999512,7885.7,7705.399780,27400.0,91.020370,104.967190,-0.159880,...,41.579,416.0,144.640261,28750.0,13.147749,17.21,8835.7,1680247.0,58.421,1.544014
Algeria,99.990051,100.0,7.744218e+06,413601.992188,95000.0,19635.999756,2381740.0,93.515851,17.025957,2.051355,...,28.541,309.0,7.619958,2381740.0,7.105500,7.50,96361.0,28977628.0,71.459,2.910068
American Samoa,NaN,NaN,0.000000e+00,49.000001,3047.0,175.000000,200.0,99.696437,278.705000,-0.127294,...,12.802,10.0,179.401159,200.0,8.708522,4.27,3067.0,48605.0,87.198,-0.172673
Andorra,100.000000,100.0,0.000000e+00,187.800007,0.0,160.000000,470.0,100.000000,164.461702,-0.919470,...,11.752,219.0,2833.227680,470.0,21.190930,21.19,0.0,68213.0,88.248,-1.029674

In [21]:
#remover all row with na
df2=df2.dropna()
df2.shape

(197, 22)

In [22]:
#create a list with all the names of countries
countriesList=type (list(df2.index))

#standarizaco
from sklearn.preprocessing import StandardScaler
df2=standardScaler().fit_transformation(df2)

NameError: name 'standardScaler' is not defined

In [ ]:
from sklearn.preprocessing

In [23]:
colList=[]
for col1is df2:
    colList.append(coll)
colList

SyntaxError: invalid syntax (<ipython-input-23-977902171874>, line 2)